apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    frontend http-in
      bind *:80
      default_backend backend-server

    backend backend-server
      balance roundrobin
      server server1 192.168.254.158:8001
      server server2 192.168.254.158:8002
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
  labels:
    app: haproxy
spec:
  type: NodePort
  selector:
    app: haproxy
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-deployment
  labels:
    app: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: haproxy:1.7-alpine
          volumeMounts:
            - name: config-volume
              mountPath: /usr/local/etc/haproxy
          ports:
            - containerPort: 80
      volumes:
        - name: config-volume
          configMap:
            name: haproxy-config
---
