apiVersion: v1
kind: Service
metadata:
  name: headless-nginx-01
spec:
  ports:
    - name: server-01
      port: 80
      targetPort: 8001
---
apiVersion: v1
kind: Endpoints
metadata:
  name: headless-nginx-01
subsets:
  - addresses:
      - ip: 192.168.254.158
    ports:
      - name: server-01
        port: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: headless-nginx-02
spec:
  ports:
    - name: server-02
      port: 80
      targetPort: 8002
---
apiVersion: v1
kind: Endpoints
metadata:
  name: headless-nginx-02
subsets:
  - addresses:
      - ip: 192.168.254.158
    ports:
      - name: server-02
        port: 8002
---
